// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`
// but written manually because Wrangler runtime crashes on this Windows machine.

interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	IMAGES: Fetcher;
	ASSETS: Fetcher;
	NEXTJS_ENV: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
